# action.yml
name: 'Cargo Release'
description: 'Releases a Cargo project'
inputs:
  dry_run:  
    description: 'Run a dry release. Default: false'
    required: false
  version:
    description: 'Version to update to. Required'
    required: true
  token:
    description: 'GITHUB_TOKEN for pushing to repo. Required.'
    required: true
  remote:
    required: false
    description: 'Set the git remote name to push too. Note "origin" will probably fail in most cases. Default: "cargo"'
outputs:
  tag: 
    description: 'The tag released'
runs:
  using: 'docker'
  image: 'docker://mooretodd/cargo-release-action:latest'